version: '1.0'

services:

  ###################-CLIENT-##########################
  #client:
  #  container_name: client
  #  build: ./Client
  #  ports:
  #    - "3000:3000"
  #  depends_on:
  #    - grpc-server
  #  networks:
  #  - app-network
  
  ###################-GRPC_SERVER-##########################
  grpc-server:
    container_name: grpc-server
    build: ./Server
    ports:
      - "50051:50051"
    depends_on:
      - redis1
      - redis2
      - redis3
    networks:
    - app-network

  ###################-REDIS-##########################
  redis1:
    container_name: redis1
    image: bitnami/redis:7.0.10-debian-11-r6
    restart: always
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
    - app-network
    command:
      [
        "redis-server",
        "--bind",
        "redis1",
        "--maxmemory 2mb",
        "--maxmemory-policy allkeys-lru",
        "--loglevel verbose",
        "--protected-mode no"  
      ]


  redis2:
    container_name: redis2
    image: bitnami/redis:7.0.10-debian-11-r6
    restart: always
    ports:
      - "6380:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
    - app-network
    command:
      [
        "redis-server",
        "--bind",
        "redis2",
        "--maxmemory 2mb",
        "--maxmemory-policy allkeys-lfu",
        "--loglevel verbose",
        "--protected-mode no"
      ]

  redis3:
    container_name: redis3
    image: bitnami/redis:7.0.10-debian-11-r6
    restart: always
    ports:
      - "6381:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
    - app-network
    command:
      [
        "redis-server",
        "--bind",
        "redis3",
        "--maxmemory 2mb",
        "--maxmemory-policy allkeys-random",
        "--loglevel verbose",
        "--protected-mode no"
      ]

##################-NETWORKS-##########################
networks:
  app-network:
    driver: bridge