version: '1.0'

#Borrar cache: docker system prune --all --force --volumes
services:
  ###################-GRPC_SERVER-##########################
  grpc-server:
    container_name: grpc-server
    build: ./Server
    ports:
      - "50051:50051"
    depends_on:
      - redis1
      - redis2
      - redis3
    networks:
    - app-network

  ###################-REDIS-##########################
  #politicas de cache
  # 1 "--maxmemory-policy allkeys-lru",
  # 2 "--maxmemory-policy allkeys-lfu",
  # 3 "--maxmemory-policy allkeys-random",
  redis1:
    container_name: redis1
    image: bitnami/redis:7.0.10-debian-11-r6
    restart: always
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
    - app-network
    command:
      [
        "redis-server",
        "--bind",
        "redis1",
        "--maxmemory 980kb",
        "--maxmemory-policy allkeys-lru",
        "--loglevel verbose",
        "--protected-mode no",
        "--save ''",  
      ]


  redis2:
    container_name: redis2
    image: bitnami/redis:7.0.10-debian-11-r6
    restart: always
    ports:
      - "6380:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
    - app-network
    command:
      [
        "redis-server",
        "--bind",
        "redis2",
        "--maxmemory 980kb",
        "--maxmemory-policy allkeys-lru",
        "--loglevel verbose",
        "--protected-mode no",
        "--save ''",
      ]

  redis3:
    container_name: redis3
    image: bitnami/redis:7.0.10-debian-11-r6
    restart: always
    ports:
      - "6381:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
    - app-network
    command:
      [
        "redis-server",
        "--bind",
        "redis3",
        "--maxmemory 980kb",
        "--maxmemory-policy allkeys-lru",
        "--loglevel verbose",
        "--protected-mode no",
        "--save ''",
      ]

##################-NETWORKS-##########################
networks:
  app-network:
    driver: bridge